apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "python-app.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "python-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "python-app.name" . }}
    spec:
      containers:
      - name: app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

        envFrom:
        - configMapRef:
            name: {{ include "python-app.fullname" . }}-config
        - secretRef:
            name: {{ include "python-app.fullname" . }}-secret

        volumeMounts:
        - name: data
          mountPath: /app/data

      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "python-app.fullname" . }}-pvc