apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: login-app
  template:
    metadata:
      labels:
        app: login-app
    spec:
      containers:
      - name: login-ingress
        image: your-dockerhub/login-ingress:latest
        ports:
        - containerPort: 80

        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secret

        volumeMounts:
        - name: data-volume
          mountPath: /app/data

      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: pvc-data